### 

@baseURL = http://localhost:{{PORT}}/api
@email = test@test.com
@name = Test User
@newPassword = password456
@password = password123


### Create user

POST {{baseURL}}/users HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "name": "{{name}}",
  "password": "{{password}}"
}


### Login

# @name login

POST {{baseURL}}/auth/sessions HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


### Get all users (admin only)

GET {{baseURL}}/users HTTP/1.1
Authorization: Bearer {{login.response.body.$.token}}


### Get user by id

GET {{baseURL}}/users/{{login.response.body.$.id}} HTTP/1.1
Authorization: Bearer {{login.response.body.$.token}}


### Update user

PATCH {{baseURL}}/users/{{login.response.body.$.id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
  "email": "{{email}}",
  "name": "{{name}}",
  "password": "{{newPassword}}"
}


### Login with new password (verifies update worked)

# @name loginNewPassword

POST {{baseURL}}/auth/sessions HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{newPassword}}"
}


### Refresh token

PUT {{baseURL}}/auth/sessions HTTP/1.1
Authorization: Bearer {{loginNewPassword.response.body.$.refreshToken}}


### Revoke token

DELETE {{baseURL}}/auth/sessions HTTP/1.1
Authorization: Bearer {{loginNewPassword.response.body.$.refreshToken}}


### Delete user (uses new token since refresh token was revoked)

DELETE {{baseURL}}/users/{{login.response.body.$.id}} HTTP/1.1
Authorization: Bearer {{loginNewPassword.response.body.$.token}}


### 

# ### get all users
# # GET "{{usersURL}}" HTTP/1.1
# Content-Type: application/json
# ### update user
# # PUT "{{usersURL}}" HTTP/1.1
# Content-Type: application/json
# # {
# "email": "{{email}}",
# "password": "{{password}}"
# }
# ### delete user
# # DELETE "{{usersURL}}" HTTP/1.1
# Content-Type: application/json
# # {
# "email": "{{email}}",
# "password": "{{password}}"
# }
