### 

@email = test@test.com
@loginURL = http://localhost:{{PORT}}/api/auth/login
@name = Test User
@newPassword = password456
@password = password123
@usersURL = http://localhost:{{PORT}}/api/users


### create user

POST {{usersURL}} HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "name": "{{name}}",
  "password": "{{password}}"
}


### login

POST {{loginURL}} HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


### update user

PUT {{usersURL}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
  "email": "{{email}}",
  "name": "{{name}}",
  "password": "{{newPassword}}"
}


### login with new password

POST {{loginURL}} HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{newPassword}}"
}


### 

# ### get all users
# # GET "{{usersURL}}" HTTP/1.1
# Content-Type: application/json
# ### update user
# # PUT "{{usersURL}}" HTTP/1.1
# Content-Type: application/json
# # {
# "email": "{{email}}",
# "password": "{{password}}"
# }
# ### delete user
# # DELETE "{{usersURL}}" HTTP/1.1
# Content-Type: application/json
# # {
# "email": "{{email}}",
# "password": "{{password}}"
# }
